# model path
motion_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/motion.pt"
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/policy.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/scene53.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [
  100, 100, 100, 150, 40, 40,
  100, 100, 100, 150, 40, 40,
  300, 300, 300,
  200, 200, 200, 100, 20, 20, 20,
  10.0, 10.0, 10.0, 10.0,
  10.0, 10.0,
  10.0, 10.0,
  10.0, 10.0,
  10.0, 10.0,
  200, 200, 200, 100, 20, 20, 20,
  10.0, 10.0, 10.0, 10.0,
  10.0, 10.0,
  10.0, 10.0,
  10.0, 10.0,
  10.0, 10.0,]
# 关节速度
kds: [
       2, 2, 2, 4, 2, 2,
       2, 2, 2, 4, 2, 2,
       5, 5, 5,
       4, 4, 4, 4, 1, 0.5, 0.5,
       2, 2, 2, 2,
       2, 2,
       2, 2,
       2, 2,
       2, 2,
       4, 4, 4, 4, 1, 0.5, 0.5,
       2, 2, 2, 2,
       2, 2,
       2, 2,
       2, 2,
       2, 2,]

# 为后17个关节设置稳定的默认姿态
default_angles:
  [ -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
    -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
    0.0,  0.0,  0.0,
    0.0,  0.0,  0.0,   0.0,  0.0,  0.0,  0.0,
    0.0,  0.0,  0.0, 0.0,
    0.0,  0.0,
    0.0,  0.0,
    0.0,  0.0,
    0.0,  0.0,
    0.0,  0.0,  0.0,   0.0,  0.0,  0.0,  0.0,
    0.0,  0.0,  0.0, 0.0,
    0.0,  0.0,
    0.0,  0.0,
    0.0,  0.0,
    0.0,  0.0,
  ]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 456

cmd_init: [0, 0, 0]

height_cmd: 0.8
min_height: 0.30
max_squat_depth: 0.3

obs_history_len: 6